version: '3.0'
services:
  rasa:
    container_name: rasa-server
    build:
      context: .
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
    depends_on:
      - action_server
  action_server:
    container_name: rasa-actions
    build:
      context: actions
    volumes:
      - ./actions:/app/actions
    ports:
      - 5055:5055
