version: '3.0'
services:
  rasa:
    container_name: rasa-server
    build:
      context: ./../../
      dockerfile: ./Docker/rasa/server/Dockerfile
    ports:
      - 5005:5005
    volumes:
      - "./../../logs:/app/logs"
    depends_on:
      - action_server
  action_server:
    container_name: rasa-actions
    build:
      context: ./../../
      dockerfile: ./Docker/rasa/actions/Dockerfile
    ports:
      - 5055:5055
    volumes:
      - "./../../actions:/app/actions"
volumes:
  logs:
  actions:
