version: '3.0'
services:
  redis:
    image: redis:7.0.4-bullseye
    container_name: redis
    ports:
      - 6379:6379
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass redis-password
