name: Build Rasa model

on:
  push:
    paths:
      - ".github/workflows/build-model.yml"
      - "data/**"
      - "config.yml"
      - "domain.yml"
      - "endpoints.yml"
      - "credentials.yml"

jobs:
  build:
    name: Train model
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Train

    #- name: Run container (train)
    #  run: docker run -v "$(pwd)/models:/app/models" rauldpm/tfg-rasa:build

    #- name: Change model name
    #  run: mv models/*.tar.gz models/model.tar.gz

    # Upload file

    - name: Setup - gcloud / gsutil
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_JSON_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}
        export_default_credentials: true

    - name: as
      run: touch models/asd

    - name: Deploy
      run: gsutil rsync -r models gs://${{ secrets.GCP_BUCKET }}