name: Build Rasa model

on: push

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Change location
      run: cd Docker/build

    - name: list
      run: ls .