name: Build Rasa model

on:
  push:
    paths:
      - ".github/workflows/build-model.yml"
      - "data/**"
      - "config.yml"
      - "domain.yml"
      - "endpoints.yml"
      - "credentials.yml"

jobs:
  build:
    name: Train model
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Run container (train)
      run: docker run -v "$(pwd)/models:/app/models" rauldpm/tfg-rasa:build

    - name: Change model name
      run: mv models/*.tar.gz models/model.tar.gz
