name: Build Rasa model

on: push

jobs:
  build:
    if: github.event_name = 'push'

    steps:
      - name: Train model
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          rasa_version: "3.1.1"
        test_type: all
