name: Build Rasa model

on: push

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set docker
      uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true

    - name: Build
      run: docker build -t train Docker/build/
