name: Build Rasa model

on: push

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set docker
      uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true

    - name: Copy dockerfile
      run: cp Docker/build/Dockerfile .

    - name: Build container
      run: docker build -t train .

    - name: Run container (train)
      run: docker run --rm -v $(pwd)/models:/app/models train:latest

    - name: Change model name
      run: mv models/*.tar.gz models/model.tar.gz

    - name: list
      run: ls models/
