name: Build Rasa model

on:
  push:
    paths:
      - ".github/workflows/build-model.yml"
      - "data/**"
      - "config.yml"
      - "domain.yml"
      - "endpoints.yml"
      - "credentials.yml"

jobs:
  build:
    name: Train model
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to GitHub Package Registry
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USER }} --password-stdin

    - uses: docker://rauldpm/tfg-rasa:build

    - name: Run container (train)
      run: docker run -v "$(pwd)/models:/app/models" tfg-rasa:build

    - name: Change model name
      run: mv models/*.tar.gz models/model.tar.gz
