name: Tests

# Build and push to DockerHub the builder container
# This container will reduce the train process (build-model.yml)
on:
  pull_request:
    branches:
      - "*"
  push:
    paths:
      - "data/**"
      - "config.yml"
      - "domain.yml"
      - "endpoints.yml"
      - "credentials.yml"

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Train model

      - name: Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run container (train)
        run: docker run -v "$(pwd)/models:/app/models" rauldpm/tfg-rasa:build

      # Run tests

      - name: Create test results directory
        run: mkdir results

      - name: Run data validate test
        run: docker run -v "$(pwd)/models:/app/models" -v "$(pwd)/results:/app/results" rauldpm/tfg-rasa:testing data-validate 2>&1 | tee -a results/output_data_validate.txt

      - name: Run stories test
        run: docker run -v "$(pwd)/models:/app/models" -v "$(pwd)/results:/app/results" rauldpm/tfg-rasa:testing test 2>&1 | tee -a results/output_stories_tests.txt
